version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    env_file: .env
    command: start-dev --http-port=8080
    ports:
      - "8080:8080"
  app:
    build: .
    env_file: .env
    environment:
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    ports:
      - "8081:8080"
    depends_on:
      - keycloak